import NavBar from "@/components/layout/nav";
import AppProvider from "@/components/provider";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import Loading from "./loading";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  teams,
  mail,
}: Readonly<{
  teams: React.ReactNode;
  mail: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <AppProvider>
          <NavBar />
          <main className="px-2 w-full h-screen">
            <Suspense fallback={<Loading />}>
              <div className="h-full py-10">
                <ResizablePanelGroup direction="horizontal">
                  <ResizablePanel defaultSize={50} minSize={10}>
                    {teams}
                  </ResizablePanel>
                  <ResizableHandle />
                  <ResizablePanel defaultSize={50} minSize={10}>
                    {mail}
                  </ResizablePanel>
                </ResizablePanelGroup>
              </div>
            </Suspense>
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
